### ISSUE TITLE
첫 번째 gpt_api 부분부터 난관에 봉착해 문의남깁니다.

### ISSUE THREAD

**Issue by CBack83** [saintdragon2/gpt_powered_dj_book_2023#1]
안녕하세요, 제가 깃허브가 처음이라 여기에 문의를 남기면 되는 건지 모르겠습니다. 혹시 번지 수를 잘못 찾아왔다면 말씀해주세요.

문의드리고 싶은 것은 아래와 같습니다.

우선 저는 파이썬 초보입니다. 
열심히 책을 따라 하고 있다가 46페이지에서 막혔고, 정보를 찾다가 이곳 깃허브까지 찾아왔습니다. 
덕분에 openai 최신 라이브러리는 삭제하고 다시 0.28.1 로 설치했습니다. 설치하고 run 해보니 아래와 같은 에러 메시지가 나옵니다.

내용을 보면 할당량을 다 썼다는 것 같은데, 저는 chatGPT를 유료로 이용하면서 책을 따라하는 과정에서 api key를 처음 발급받았거든요. 문제가 무엇인지 혹시 도움을 받을 수 있을까요? (API 크레딧은 별도로 결제했습니다)

----
예외가 발생했습니다. RateLimitError
You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.
  File "/Users/james/Documents/공부(Study)/GPTnPython/very_first_gpt_api_ori.py", line 7, in ask_to_gpt_35_turbo
    response = openai.ChatCompletion.create(
  File "/Users/james/Documents/공부(Study)/GPTnPython/very_first_gpt_api_ori.py", line 22, in <module>
    r = ask_to_gpt_35_turbo(users_request)
openai.error.RateLimitError: You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.

![image](https://github.com/saintdragon2/gpt_powered_dj_book_2023/assets/11377124/62840b62-0a9d-4052-9064-c094f149a0aa)
![image](https://github.com/saintdragon2/gpt_powered_dj_book_2023/assets/11377124/362ecd7d-e3e5-4644-b056-f208cd6308c0)
![image](https://github.com/saintdragon2/gpt_powered_dj_book_2023/assets/11377124/82b8ee23-6d53-4f23-a7ce-fa9740e7d329)

**Comment by CBack83** [comment]
앗? 해결되었습니다.
우선 API 결제한 후에 API 키 다시 발급하고 재시도했더니 되었어요!

API 결제와 chatGPT 이용 결제와는 다른 것인데 제가 몰랐었어요. 해결되었습니다ㅎㅎ

**Comment by saintdragon2** [comment]
맞습니다. 저도 처음에 헷갈렸는데 API와 ChatGPT결제를 중복으로 해야 하더라고요. 하지만 API는 사용량만큼만 부과되니까 그러려니 하고 사용하고 있습니다.
